### ISSUE TITLE
Error when mvn package

### ISSUE THREAD

**Issue by Wuaner** [tuanhiep/mqtt-jmeter-plugin#7]
I am using JDK 1.6, Maven 3.2.3.

Details:

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/lee/Opensource/mqtt-jmeter/src/main/java/org/apache/jmeter/protocol/mqtt/control/gui/MQTTPublisherGui.java:[138,19] type javax.swing.JComboBox does not take parameters
[ERROR] /home/lee/Opensource/mqtt-jmeter/src/main/java/org/apache/jmeter/protocol/mqtt/control/gui/MQTTPublisherGui.java:[138,57] type javax.swing.JComboBox does not take parameters
[INFO] 2 errors

**Comment by ghost** [comment]
JComboBox doesn't takes parameters in jdk 1.6, you must use jdk 1.7

**Comment by Wuaner** [comment]
Thanks.
